image: alpine/edge
secrets:
- 1b3fe3d9-ee86-4c7e-bd35-d0c87b6e12a9
sources:
- git+ssh://git@git.sr.ht/~aaronkelly/crust
tasks:
- push-to-github: |-
    cd crust
    git checkout master
    git remote set-url origin git@github.com:aaronpkelly/crust.git
    git push -u origin master